### PR TITLE
Jump to Netlify

### PR DESCRIPTION
**Pull request by j0k3r**
It'll be easier to handle redirection for example.
The wallabag doc website is already hosted on Netlify.

### CODE REVIEW

**Comment by jbleuzen** [comment]
Could you remove the copy of `CNAME` in the `eleventy.config.js` file please (line 28) ?

**Comment by j0k3r** [comment]
Looks like `README.md` isn't properly ignored 😕 
https://deploy-preview-4--wallabag-website.netlify.app/readme/

**Review by nicosomb — APPROVED** [review]

**Comment by jbleuzen** [comment]
> Looks like `README.md` isn't properly ignored 😕
> https://deploy-preview-4--wallabag-website.netlify.app/readme/

Maybe you can use the `.eleventyignore` file to ignore `README.md`

**Comment by j0k3r** [comment]
@jbleuzen seems to work better 🤷🏼

**Review by nicosomb — APPROVED** [review]

**Review by jbleuzen — APPROVED** [review]
Yes better !

**Pull request merged**
