### PR TITLE
Changed OG data

### LINKED ISSUE #69: Please fix og:title and add date field
Hi @nicosomb, following-up https://github.com/wallabag/wallabag/issues/7763 I guess the following changes could fix the missing title in wallabag's grab of wallabag.org article and add a new date line.

File:  _includes/_head.html
```html
// change extisting og:title line to
<meta property="og:title" content="{{ title }}">
// add new line
<meta name="date" content="{{ date }}">
```

As I can't test the changes, I will not PR this.

Edit:
just saw it: this line should be changed, too. Or every article contains the site-description as lead paragraph:
```html
<meta name="description" content="{{ site.description }}">
```

### PR DESCRIPTION
**Pull request by nicosomb**
Should fix #69

### CODE REVIEW

**Comment by nicosomb** [comment]
@HolgerAusB You can have a preview here: https://deploy-preview-70--wallabag-website.netlify.app/news/20241031-migrate-from-omnivore/

**Comment by HolgerAusB** [comment]
- og:title is good now
- date is in wrong format and is not parsable by wallabag. I am not a developer, but try `{{ page.date.toISOString }}` which should result in something like: `2024-11-01T09:00:00.000Z`
- for 'description' without 'og:' i might messing up things. I don't know, if this should contain the site.description or the page excerpt, sorry. But...
- og:description line is now missing completely in the template, this should contain an excerpt of current page. I assume 11ty is not auto-generating an excerpt. So you either need to have a handwritten short-line in your pages head or using a plugin which is just shorten the body. We don't need this for wallabag fetch but it could beautifying the preview cards in social media.
```
---
title: the title
date: 2024-11-01
desciption: Short excerpt of the body text here
---
```

**Comment by nicosomb** [comment]
@HolgerAusB it should be better with my latest changes ;-)

**Comment by HolgerAusB** [comment]
@nicosomb. The date is now different but still not in the correct format (in my opinion, which might be wrong). But now it is parseable by wallabag, so I am fine with it. Thank you.

**Review by HolgerAusB — APPROVED** [review]

**Comment by nicosomb** [comment]
What is the correct format?

**Comment by HolgerAusB** [comment]
as far as I found on most sources when writing site configs, it should be more like this:
`2024-11-01T09:00:00.000Z`. But as I said, maybe I am wrong

And google said, that should be working with this in your _head template:
`{{ page.date.toISOString }}`

**Pull request merged**
